### ISSUE TITLE
Pins Positioned Incorrectly

### ISSUE THREAD

**Issue by senica** [manifestinteractive/jqvmap#238]
#### Overview:

When the container map is not positioned at 0,0, the pins are wrongly placed on the map.
This also happens if there is content before the map on the page.

#### Acceptance Criteria:
Expected that pins to be centered on region

#### Steps to Duplicate _( required for detects )_:

http://codepen.io/anon/pen/QEbWvQ
Use any of the examples, move the map anywhere else on the screen either by adding content before it  or making absolutely positioned.

#### Relevant Documentation _( optional )_

http://codepen.io/anon/pen/QEbWvQ

**Comment by manifestinteractive** [comment]
If you are changing the way CSS positioning is being used for the map, you simply need to update your CSS for the pins to reflect your CSS changes.  The CSS we have is just for example usage, you are free, as you have done, to change the CSS however you see fit.  It just means that you'll also need to make changes to address things that break with your CSS updates.

For your specific issue, simply adding the following CSS addresses the issue.

```css
#vmap{
  /* This breaks it also */
  position: absolute;
  top: 100px;
  left: 40px;
}
.jqvmap-pin {
  position: fixed !important;
}
```

Forked codepen here:  http://codepen.io/manifestinteractive/pen/mEJdxR
